services:
  mariadb:
    image: mariadb:11
    container_name: mariadb_laravel
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_DATABASE: bitnami_myapp
      MARIADB_USER: bn_myapp
      MARIADB_PASSWORD: b1tnam1_my@pp
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - laravel-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5


  application:
    image: bitnamilegacy/laravel:latest
    container_name: laravel_app
    environment:
      LARAVEL_DATABASE_TYPE: mysql
      LARAVEL_DATABASE_HOST: mariadb
      LARAVEL_DATABASE_PORT_NUMBER: 3306
      LARAVEL_DATABASE_NAME: bitnami_myapp
      LARAVEL_DATABASE_USER: bn_myapp
      LARAVEL_DATABASE_PASSWORD: b1tnam1_my@pp
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - laravel-network


volumes:
  mariadb_data:


networks:
  laravel-network:
    driver: bridge